#pragma kernel CSMain
#define NUM_THREADS 8

float3 Size;
RWTexture3D<int> Write;

[numthreads(NUM_THREADS, NUM_THREADS, NUM_THREADS)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	int obstacle = 0;

	if (id.x - 1 < 0) obstacle = 1;
	if (id.x + 1 > (int)Size.x - 1) obstacle = 1;

	if (id.y - 1 < 0) obstacle = 1;
	if (id.y + 1 > (int)Size.y - 1) obstacle = 1;

	if (id.z - 1 < 0) obstacle = 1;
	if (id.z + 1 > (int)Size.z - 1) obstacle = 1;

	Write[id] = obstacle;
}
